name = "ousevoidindonesia"
compatibility_date = "2026-07-15"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "ousevoid-db"
database_id = "MASUKIN_ID_DATABASE_D1_LU_DISINI"
